data:
  save_dir: "./data"
  train_batches: [1, 2, 3]
  val_batches: [4]
  random_state: 42

training:
  batch_size: 64
  num_workers: 2
  num_epochs: 15
  learning_rate: 0.001

model:
  n_classes: 10

artifacts:
  save_dir: "./artifacts/3batch"
  best_model_name: "best_model.pth"
